version: "2"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: suggestit
      POSTGRES_DB: suggestit
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      
      PRIT_AUTH_KEY: 123456789
      PRIT_PASSWORD: password
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app/

  #gotify:
  #  image: cthit/gotify:latest
  #  environment:
  #    GOTIFY_PRE-SHARED-KEY: "123abc"
  #    GOTIFY_MOCK-MODE: "true"
  #  ports:
  #    - 1337:8080
