version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: suggestit
      POSTGRES_DB: suggestit
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

  backend:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    environment:
      SUGGESTIT_POSTGRES_USER: suggestit
      SUGGESTIT_POSTGRES_PASSWORD: password
      SUGGESTIT_POSTGRES_HOST: db
      SUGGESTIT_POSTGRES_PORT: 5432
      SUGGESTIT_POSTGRES_DB: suggestit

      GIN_MODE: ""
      MOCK_MODE: "True"
      AUTH_SECRET: secret
      CLIENT_ID: id
      GAMMA_URL: http://gamma-backend:8081
      REDIRECT_GAMMA_URL: http://localhost:8081
      CALLBACK_URL: http://localhost:3001/callback
      ALLOWED_GROUP: prit
      COOKIE_DOMAIN: localhost
    volumes:
      - ./backend/:/go/src/app

    ports:
      - 5000:3000

  frontend:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./frontend/src:/usr/src

  gamma-db:
    image: postgres:10
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password

  gamma-frontend:
    image: cthit/gamma-frontend:development
    network_mode: host
    ports:
      - 3000:3000

  gamma-backend:
    image: cthit/gamma-backend
    environment:
      # Default admin user name = admin
      # Default admin password  = password

      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: gamma-db
      DB_PORT: 5432
      DB_NAME: postgres

      REDIS_HOST: redis
      REDIS_PASSWORD: ""

      SERVER_PORT: 8081
      FRONTEND_REDIRECT_URI: http://localhost:3000/login
      SUCCESSFUL_LOGIN: http://localhost:3000
      CORS_ALLOWED_ORIGIN: http://localhost:3000
      COOKIE_DOMAIN: localhost
      PRODUCTION: "false"
      IS_MOCKING_CLIENT: "true"
      DEFAULT_REDIRECT_URI: http://localhost:3001/callback
 
    ports:
      - 8081:8081

  redis:
    image: redis:5.0
