version: "2"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: suggestit
      POSTGRES_DB: suggestit
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    environment: 
      SUGGESTIT_POSTGRES_USER: suggestit
      SUGGESTIT_POSTGRES_PASSWORD: password
      SUGGESTIT_POSTGRES_HOST: db
      SUGGESTIT_POSTGRES_PORT: 5432
      SUGGESTIT_POSTGRES_DB: suggestit

      AUTH_SECRET: hellotherethisisasecret
      CLIENT_ID: thisisaclientid

      GOTIFY_URL: http://gotify:8080
      GOTIFY_PRE_SHARED_KEY: 123abcc
      ENABLE_EMAIL: "True"

    volumes:
      - ./backend/:/go/src/app
    
    ports:
      - 5000:3000

  frontend:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src

  gotify:
    image: cthit/gotify:latest
    environment:
      GOTIFY_PRE-SHARED-KEY: "123abcc"
      GOTIFY_MOCK-MODE: "true"
    ports:
      - 1337:8080
