version: "2"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: suggestit
      POSTGRES_DB: suggestit
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080
  backend:
    image: cthit/suggestit-backend
    environment: 
      SUGGESTIT_POSTGRES_USER: suggestit
      SUGGESTIT_POSTGRES_PASSWORD: password
      SUGGESTIT_POSTGRES_HOST: db
      SUGGESTIT_POSTGRES_PORT: 5432
      SUGGESTIT_POSTGRES_DB: suggestit

      AUTH_SECRET: thisisasecret
    ports:
      - 5000:5000

  frontend:
    image: cthit/suggestit-frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/src/app/