openapi: 3.0.0
info:
  description: This is the backend used in the application
    [suggestIT](https://suggestit.chalmers.it). The application is a suggestion
    box for the committee P.R.I.T.
  version: 1.0.0
  title: SuggestIT backand
  contact:
    email: digit@chalmers.it

paths:
  /api/auth/withCode:
    post:
      tags:
        - Authentication
      summary: Exchange Gamma authentication code with cookie
      parameters:
        - in: query
          name: code
          description: Gamma authentication code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Attached authentication cookie
        "401":
          description: You are not P.R.I.T.
  /api/checkLogin:
    get:
      tags:
        - Authentication
      summary: Checks if the user is logged in
      parameters:
        - in: cookie
          name: suggestit
          description: Gamma authntication token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User is logged in
        "401":
          description: User is not logged in

  /api/login:
    get:
      tags:
        - Authentication
      summary: Redirects the user to Gamma authentication site
      responses:
        "301":
          description: Redirect to Gamma

  /api/logout:
    get:
      tags:
        - Authentication
      summary: Removes authentication cookie and makes user unauthenticated
      parameters:
        - in: cookie
          name: suggestit
          description: Gamma authntication token
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "User has been logged out"

  /api:
    get:
      tags:
        - Api
      summary: Get all suggestions
      parameters:
        - in: cookie
          name: suggestit
          description: Gamma authntication token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of all suggestions in the suggestion box
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Suggestions"
        "401":
          description: You are not P.R.I.T.
    post:
      tags:
        - Api
      summary: Create a new suggestion
      parameters:
        - in: cookie
          name: suggestit
          description: Gamma authntication token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Suggestion"
        description: the token from /api/authorization
        required: true
      responses:
        "200":
          description: Suggestion created

  /api/suggestion:
    get:
      tags:
        - Api
      summary: Get specific suggestion
      parameters:
        - in: cookie
          name: suggestit
          description: Gamma authntication token
          required: true
          schema:
            type: string
        - in: query
          name: Id
          description: requesting one specific suggestion
          required: false
          schema:
            type: string
      responses:
        "200":
          description: One singel suggestion
        "401":
          description: You are not P.R.I.T.

  /api/delete:
    delete:
      tags:
        - Api
      summary: Delete a specific suggestion
      parameters:
        - in: cookie
          name: suggestit
          description: Gamma authntication token
          required: true
          schema:
            type: string
        - in: query
          name: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "null"
        "401":
          description: You are not P.R.I.T.

    put:
      tags:
        - Api
      summary: Deletes multiple suggestions at once
      parameters:
        - in: cookie
          name: suggestit
          description: Gamma authntication token
          required: true
          schema:
            type: string
        - in: body
          name: ids
          required: true
          schema:
            $ref: "#/components/schemas/idarray"
      responses:
        "200":
          description: "Suggestions deleted"
        "401":
          description: "You are not P.R.I.T."

servers:
  - url: http://localhost:5000
components:
  schemas:
    idarray:
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
            format: uuid
    Suggestions:
      type: array
      items:
        type: object
        properties:
          author:
            type: string
            example: Hello
          id:
            type: string
            format: uuid
          text:
            type: string
          timestamp:
            type: string
            format: datetime
          title:
            type: string
    Suggestion:
      type: object
      properties:
        author:
          type: string
        text:
          type: string
        title:
          type: string
